name: Java CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_zulu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '18', '19', '21' ]
    name: Java ${{ matrix.java }} Zulu build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java }} Zulu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn -B test --file pom.xml

  test_temurin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '18', '19', '21' ]
    name: Java ${{ matrix.java }} Temurin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java }} Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn -B test --file pom.xml

